### ISSUE TITLE
Murdock not working for non-master branches

### ISSUE THREAD

**Issue by miri64** [kaspar030/murdock#1]
There are a few instances where I identified problems in the script, if `base_branch` is not master.

Directly in at the start:

```
[…]
+ git rebase 2016.04-branch
 or later) by using -b with the checkout command again. Example:

  git checkout -b 

HEAD is now at f6e3fbb... tests: adapt libfixmath tests for change
+ git rebase 2016.04-branch
Current branch HEAD is up to date.
+ build
+ mkdir bin
+ cp /srv/riot-ci/riot-ci/scripts/build_all.sh bin
+ cp /srv/riot-ci/riot-ci/scripts/ccache bin
++ git diff --name-only master -- core/include
fatal: bad revision 'master'
```

Could not identify where in this repo this was coming from (side-question: where is `build_all.sh` btw)

The next line after this looks strange, btw:
```
+ '[' -n '' ']'
```

The other occurence is in the static tests:

```
BUILD OUTPUT of group static-tests:
fatal: Needed a single revision
invalid upstream master
No rebase in progress?
```

This might be however due to [build_and_test.sh](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/travis-scripts/build_and_test.sh) (if that is used) only referring to master.

**Comment by kaspar030** [comment]
```build_all.sh``` is nowhere public, as I changed it a lot in the beginning. It doesn't really belong into the murdock repo, as it is RIOT specific. Will have to find a place...

Anyhow, the failed line was a check whether anything in "core/include" has changed, compared to master. That is fixed now.

I'll close this here, see https://github.com/RIOT-OS/RIOT/issues/5518 for the RIOT issue.

Thanks for reporting!
